#!/usr/bin/env bash

docker run --rm --mount type=bind,source=$(pwd),target=/home/docker/my-setup,readonly -it my-setup bash -c "ansible-playbook -v -e 'ansible_become_pass=docker' -t '$1' my-setup/local.yml; bash"

