#!/usr/bin/env bash
# Run this script as ./run-test ubuntu

# docker run --rm -v "$(pwd)":/home/docker/my-setup:ro,z -it my-setup bash -c "ansible-playbook -v -e 'ansible_become_pass=docker' -t '$1' my-setup/local.yml; bash"

# add --log-level=debug for podman verbosity
podman run --rm --mount type=bind,source=$(pwd),target=/home/docker/my-setup,readonly -it my-setup bash -c "ansible-playbook -v -e 'ansible_become_pass=docker' -t '$1' my-setup/local.yml; bash"
