#!/usr/bin/env bash

remote=$(git remote -v | grep 'http')

if [[ $remote ]]; then
    echo 'Switching my-setup remote from http to ssh.'
    git remote set-url origin git@github.com:hoelter/my-setup.git
fi

