- name: Remove binary symlink for fzf
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin/fzf"
    state: absent
  tags: 
  - ubuntu
  - core
  - fzf

- name: Remove binary symlink for fzf-tmux 
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin/fzf-tmux"
    state: absent
  tags: 
  - ubuntu
  - core
  - fzf

- name: Remove symlink for fish key-bindings
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/functions/fzf_key_bindings.fish"
    state: absent
  tags: 
  - ubuntu
  - core
  - fzf

- name: Ensure local binary dir is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
  tags:
  - ubuntu
  - core
  - fzf

- name: Clone fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "{{ lookup('env', 'HOME') }}/.local/fzf"
    version: master
    update: yes
    depth: 1
  tags:
  - ubuntu
  - core
  - fzf

- name: Install fzf
  shell: cd {{ lookup('env', 'HOME') }}/.local/fzf  && ./install --bin
  tags:
  - ubuntu
  - core
  - fzf

- name: Create binary symlink for fzf
  file:
    src: "{{ lookup('env', 'HOME') }}/.local/fzf/bin/fzf"
    path: "{{ lookup('env', 'HOME') }}/.local/bin/fzf"
    state: link
  tags: 
  - ubuntu
  - core
  - fzf

- name: Create binary symlink for fzf-tmux 
  file:
    src: "{{ lookup('env', 'HOME') }}/.local/fzf/bin/fzf-tmux"
    path: "{{ lookup('env', 'HOME') }}/.local/bin/fzf-tmux"
    state: link
  tags: 
  - ubuntu
  - core
  - fzf

- name: Ensure fish functions dir is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/functions"
    state: directory
  tags:
  - ubuntu
  - core
  - fzf

- name: Create symlink for fish key-bindings
  file:
    src: "{{ lookup('env', 'HOME') }}/.local/fzf/shell/key-bindings.fish"
    path: "{{ lookup('env', 'HOME') }}/.config/fish/functions/fzf_key_bindings.fish"
    state: link
  tags: 
  - ubuntu
  - core
  - fzf
