# https://asdf-vm.com/guide/getting-started.html#_1-install-dependencies

- name: Remove asdf if it exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.asdf"
    state: absent
  tags:
  - ubuntu
  - asdf

- name: Clone asdf plugin manager
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    version: "v0.11.1"
  tags:
  - ubuntu
  - asdf

- name: Clone asdf plugin manager
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    version: "v0.11.1"
  tags:
  - ubuntu
  - asdf

- name: Create binary symlink for asdf fish completions
  file:
    src: "{{ lookup('env', 'HOME') }}/.asdf/completions/asdf.fish"
    path: "{{ lookup('env', 'HOME') }}/.config/fish/completions/asdf"
    state: link
  tags: 
  - ubuntu
  - asdf
