- name: Install core cli tools
  become: true
  apt:
    name:
    - build-essential
    - keychain # wsl2 ssh agent persistence
    - direnv
    - moreutils # https://rentes.github.io/unix/utilities/2015/07/27/moreutils-package/
      #- httpie -- consider adding through install steps here: https://httpie.io/docs/cli/debian-and-ubuntu
  tags: 
  - ubuntu
  - core
  - core-apt

- name: Ensure .local bin folder exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
  tags: 
  - ubuntu
  - core

- name: Register architecture
  shell: dpkg --print-architecture
  register: curr_arch
  tags: 
  - ubuntu
  - core
  - fd
  - batcat

- name: Remove fd if installed
  become: true
  apt:
    name: fd
    state: absent
  tags:
  - ubuntu
  - core
  - fd

- name: Register latest fd version
  shell: |
    curl --silent "https://api.github.com/repos/sharkdp/fd/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | cut -c 2-
  register: fd_ver
  tags: 
  - ubuntu
  - core
  - fd

- name: install latest fd deb release
  become: true
  apt:
    deb: 'https://github.com/sharkdp/fd/releases/latest/download/fd_{{ fd_ver.stdout }}_{{ curr_arch.stdout }}.deb'
  tags:
  - ubuntu
  - core
  - fd

- name: Remove bat if installed
  become: true
  apt:
    name: bat
    state: absent
  tags:
  - ubuntu
  - core
  - batcat

- name: Register latest batcat version
  shell: |
    curl --silent "https://api.github.com/repos/sharkdp/bat/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | cut -c 2-
  register: bat_ver
  tags: 
  - ubuntu
  - core
  - batcat

- name: Install latest batcat deb release
  become: true
  apt:
    deb: 'https://github.com/sharkdp/bat/releases/latest/download/bat_{{ bat_ver.stdout }}_{{ curr_arch.stdout }}.deb'
  tags:
  - ubuntu
  - core
  - batcat

- name: Remove ripgrep if installed
  become: true
  apt:
    name: ripgrep
    state: absent
  tags:
  - ubuntu
  - core
  - rg

- name: Register latest ripgrep version
  shell: |
    curl --silent "https://api.github.com/repos/BurntSushi/ripgrep/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'
  register: rg_ver
  tags: 
  - ubuntu
  - core
  - rg

- name: install latest ripgrep deb release
  become: true
  apt:
    # Only appears to have amd64 architecture
    deb: 'https://github.com/BurntSushi/ripgrep/releases/latest/download/ripgrep_{{ rg_ver.stdout }}_amd64.deb'
  tags:
  - ubuntu
  - core
  - rg

# May need these again at some point

#- name: Install ripgrep
#  become: true
#  apt:
#    name:
#    - ripgrep
#    #dpkg_options: 'force-overwrite'
#  tags: 
#  - ubuntu
#  - core

#- name: Assign path of fdfind
#  shell: which fdfind
#  register: fdfind_path
#  tags: 
#  - ubuntu
#  - core
#
#- name: Link fdfind into .local bin with proper alias
#  file:
#    src: '{{ item.src_dir }}'
#    path: "{{ lookup('env', 'HOME') }}/.local/bin/{{ item.dest_name }}"
#    state: link
#  with_items:
#  - { src_dir: '{{ fdfind_path.stdout }}', dest_name: fd }
#  tags: 
#  - ubuntu
#  - core

