- name: Clone dotfiles
  git:
    repo: 'https://github.com/hoelter/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    version: master
    update: no # Don't overwrite potential local changes
  tags:
  - ubuntu
  - dotfiles

- name: Install stow
  become: true
  apt:
    name: stow
  tags: 
  - ubuntu
  - dotfiles

- name: Stow dotfiles
  shell: cd {{ lookup('env', 'HOME') }}/.dotfiles && ./ubuntu-install
  tags:
  - ubuntu
  - dotfiles

