- name: Clone dotfiles
  git:
    repo: 'https://github.com/hoelter/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    version: master
    update: no # Don't overwrite potential local changes
  tags:
  - ubuntu
  - dotfiles

- name: Install stow
  become: true
  apt:
    name: stow
  tags: 
  - ubuntu
  - dotfiles

# Ensure certain config directories are created so that they're not symlinked in by stow
- name: Ensure fish functions dir is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/functions"
    state: directory
  tags:
  - ubuntu
  - dotfiles

- name: Ensure fish conf.d dir is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/conf.d"
    state: directory
  tags:
  - ubuntu
  - dotfiles

- name: Ensure completions dir is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/completions"
    state: directory
  tags:
  - ubuntu
  - dotfiles

- name: Stow dotfiles
  shell: cd {{ lookup('env', 'HOME') }}/.dotfiles && ./ubuntu-install
  tags:
  - ubuntu
  - dotfiles

