- name: Add fish ppa
  become: yes
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
  tags: 
  - ubuntu
  - fish

- name: Install fish
  become: yes
  apt:
    name: fish
  tags: 
  - ubuntu
  - fish

# - name: Assign fisher dir variable
#   stat:
#     path: "{{ lookup('env', 'HOME') }}/.config/fish/functions/fisher.fish"
#   register: fisher_func
#   tags: 
#   - ubuntu
#   - fish
#   - node

# - name: Install fisher plugin manager
#   shell: fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
#   when: fisher_func.stat.exists == False
#   tags: 
#   - ubuntu
#   - fish
#   - node
- name: Ensure fish functions dir is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/functions"
    state: directory
  tags:
  - ubuntu
  - dotfiles

- name: Ensure conf.d directory created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/conf.d"
    state: directory
  tags:
  - ubuntu
  - fish

- name: Ensure completions directory created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/completions"
    state: directory
  tags:
  - ubuntu
  - fish

# - name: Update fisher plugins
#   shell: fish -c "fisher update"
#   when: fisher_func.stat.exists == True
#   tags:
#   - fish
