- name: Add fish ppa
  become: yes
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
  tags: 
  - ubuntu
  - fish

- name: Install fish
  become: yes
  apt:
    name: fish
  tags: 
  - ubuntu
  - fish

- name: Ensure fish functions dir is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/functions"
    state: directory
  tags:
  - ubuntu
  - dotfiles

- name: Ensure conf.d directory created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/conf.d"
    state: directory
  tags:
  - ubuntu
  - fish

- name: Ensure completions directory created
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/fish/completions"
    state: directory
  tags:
  - ubuntu
  - fish

