- name: Ensure local binary dir is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
  tags:
  - golang

- name: Remove golang symlink if it exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin/go"
    state: absent
  tags: 
  - golang

- name: Remove gofmt binary to bin
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin/gofmt"
    state: absent
  tags: 
  - golang

- name: Remove golang dir if it exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/go"
    state: absent
  tags:
  - golang

- name: Download golang tarball and unarchive into local folder
  unarchive:
    # TODO: Make dynamic to grab latest version
    src: https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local"
    remote_src: yes
  tags: 
  - golang

- name: Link go binary to bin
  file:
    src: "{{ lookup('env', 'HOME') }}/.local/go/bin/go"
    path: "{{ lookup('env', 'HOME') }}/.local/bin/go"
    state: link
  tags: 
  - golang

- name: Link gofmt binary to bin
  file:
    src: "{{ lookup('env', 'HOME') }}/.local/go/bin/gofmt"
    path: "{{ lookup('env', 'HOME') }}/.local/bin/gofmt"
    state: link
  tags: 
  - golang
