# - name: Ensure nvm dir exists for install
#   file:
#     path: "{{ lookup('env', 'HOME') }}/.local/share/nvm/"
#     state: directory
#   tags: 
#   - ubuntu
#   - node

# - name: Install fisher nvm plugin
#   shell: 
#     cmd: fish -c 'fisher install jorgebucaran/nvm.fish'
#   tags: 
#   - ubuntu
#   - node

# - name: Install node with nvm
#   shell: 
#     cmd: fish -c 'nvm install {{ node_version }} && set -U nvm_default_version {{ node_version }}'
#   tags: 
#   - ubuntu
#   - node

# - name: Install node asdf dependencies
#   become: true
#   apt:
#     name:
#     - build-essential
#   tags: 
#   - ubuntu
#   - node

- name: Check if asdf is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.asdf/plugins/node"
  register: asdf_node
  tags: 
  - ubuntu
  - node

- name: Install asdf-node plugin
  shell: 
    cmd: "export PATH={{ lookup('env', 'HOME') }}/.asdf/bin:$PATH && {{ lookup('env', 'HOME') }}/.asdf/bin/asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git"
  when: asdf_node.stat.exists == False
  tags: 
  - ubuntu
  - node

- name: Install node with asdf
  shell: 
    cmd: "export PATH={{ lookup('env', 'HOME') }}/.asdf/bin:$PATH && asdf install nodejs {{ node_version }}"
  tags: 
  - ubuntu
  - node

- name: Set global node to same version
  shell: 
    cmd: "export PATH={{ lookup('env', 'HOME') }}/.asdf/bin:$PATH && asdf global nodejs {{ node_version }}"
  tags: 
  - ubuntu
  - node
