- name: Install global yarn
  shell: 
    cmd: fish -c 'nvm use {{ node_version }} && npm install -g yarn'
  tags: 
  - ubuntu
  - npm-packages

- name: Install global typescript lsp and eslint_d
  shell: 
    cmd: fish -c 'nvm use {{ node_version }} && npm install -g typescript typescript-language-server eslint_d prettier'
  tags: 
  - ubuntu
  - npm-packages

- name: Update global npm packages
  shell: 
    cmd: fish -c 'npm update -g typescript typescript-language-server eslint_d prettier'
  tags: 
  - npm-package-updates
