- name: Ensure local binary dir is created
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
  tags:
  - rider

- name: See if rider has been previously downloaded
  stat:
    path: "{{ lookup('env', 'HOME') }}/.local/Rider/Rider.sh"
  register: rider_path
  tags: 
  - rider

# TODO: Parse version from content on this page https://www.jetbrains.com/rider/download/#section=linux
# Also, rename once it's present
- name: Download rider and unarchive into .local
  unarchive:
    src: "https://download.jetbrains.com/rider/JetBrains.Rider-2022.2.2.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/.local"
    remote_src: yes
  when:
  - rider_path.stat.exists == False
  tags: 
  - rider

- name: Create binary symlink for android studio
  file:
    src: "{{ lookup('env', 'HOME') }}/.local/JetBrains Rider-2022.2.2/bin/rider.sh"
    path: "{{ lookup('env', 'HOME') }}/.local/bin/rider"
    state: link
  tags: 
  - rider

# Complete install by running rider
