# https://github.com/asdf-vm/asdf-ruby
- name: Install asdf-ruby dependencies
  become: true
  apt:
    name:
    - autoconf
    - bison
    - patch
    - rustc
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libgmp-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm6
    - libgdbm-dev
    - libdb-dev
    - uuid-dev
  tags: 
  - ruby

- name: Install ruby asdf plugin
  shell: 
    cmd: fish -c 'asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git'
  tags: 
  - ruby

- name: Install ruby with asdf
  shell: 
    cmd: fish -c 'asdf install ruby latest'
  tags: 
  - ruby

- name: Set global ruby to same version
  shell: 
    cmd: fish -c 'asdf global ruby latest'
  tags: 
  - ruby
