- name: Install plugin dependencies
  become: true
  apt:
    name:
    - urlview # tmux url plugin support
  tags: 
  - ubuntu
  - core
  - tmux
  - tmux-plugins

- name: Remove tmux plugins directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/tmux/plugins"
    state: absent
  tags:
  - ubuntu
  - core
  - tmux
  - tmux-plugins

- name: Create tmux plugins directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/tmux/plugins"
    state: directory
  tags:
  - ubuntu
  - core
  - tmux
  - tmux-plugins

- name: Clone tmux plugin manager
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/tmux/plugins/tpm"
  tags:
  - ubuntu
  - core
  - tmux
  - tmux-plugins

