- name: Install pistol dependencies
  become: true
  apt:
    name:
    - libmagic-dev # needed to support magicmime used for identifying the mimetypes
    - poppler-utils # pdftotext
  tags: 
  - pistol

- name: Install pistol with go
  shell: "env GOPATH={{ lookup('env', 'HOME') }}/.go CGO_ENABLED=1 GO111MODULE=on {{ lookup('env', 'HOME') }}/.local/bin/go install github.com/doronbehar/pistol/cmd/pistol@latest"
  tags: 
  - pistol
