# On ubuntu 22, just run apt install dotnet6

- name: Remove omnisharp dll symlink if it exists
  become: true
  file:
    path: /usr/local/bin/OmniSharp.dll
    state: absent
  tags: 
  - omnisharp

- name: Remove omnisharp binary dir if it exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/omnisharp"
    state: absent
  tags:
  - omnisharp

- name: Ensure omnisharp dir target path exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/omnisharp"
    state: directory
  tags: 
  - omnisharp

- name: Download omnisharp tarball and unarchive into local folder
  unarchive:
    # src: https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.38.2/omnisharp-linux-x64.tar.gz
    src: https://github.com/OmniSharp/omnisharp-roslyn/releases/latest/download/omnisharp-linux-x64-net6.0.tar.gz
    dest: "{{ lookup('env', 'HOME') }}/.local/omnisharp"
    remote_src: yes
  tags: 
  - omnisharp

- name: Link dll to common location for hard coded nvim config reference
  become: true
  file:
    src: "{{ lookup('env', 'HOME') }}/.local/omnisharp/OmniSharp.dll"
    path: /usr/local/bin/OmniSharp.dll
    state: link
  tags: 
  - omnisharp

#- name: Ensure omnisharp dir exists for global settings
#  file:
#    path: "{{ lookup('env', 'HOME') }}/.omnisharp"
#    state: directory
#  tags: 
##  - omnisharp
